twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/Home/Templates': home

when@test:
    twig:
        strict_variables: true
