twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/Home/Templates': home
        '%kernel.project_dir%/src/Menu/Templates': menu
        '%kernel.project_dir%/src/Carrelage/Templates': carrelage


when@test:
    twig:
        strict_variables: true
