vich_uploader:
    db_driver: orm
    mappings:
        menu_image:
            uri_prefix: /uploads/images/menus
            upload_destination: '%kernel.project_dir%/public/uploads/images/menus'
            namer: Vich\UploaderBundle\Naming\UniqidNamer