home_controllers:
    resource: ../src/Home/Controller/
    type: attribute

menu_controllers:
    resource: ../src/Menu/Controller/
    type: attribute

carrelage_controllers:
    resource: ../src/Carrelage/Controller/
    type: attribute

rendezvous_controllers:
    resource: ../src/RendezVous/Controller/
    type: attribute

catalogue_controllers:
  resource: ../src/Catalogue/Controller/
  type: attribute

configuration_controllers:
  resource: ../src/Configuration/Controller/
  type: attribute
