home_controllers:
    resource:
        path: ../src/Home/Controller/
        namespace: App\Home\Controller
    type: attribute

menu_controllers:
    resource:
        path: ../src/Menu/Controller/
        namespace: App\Menu\Controller
    type: attribute
